"""Code generation utilities for HPF.

Produces ready-to-paste Optuna search space snippets from a list of
ParameterSuggestion objects.
"""

from __future__ import annotations

from typing import Any

from hpf.models import (
    ParameterScale,
    ParameterSuggestion,
    ParameterType,
    SuggestionAction,
)


def generate_optuna_code(
    suggestions: list[ParameterSuggestion], study_name: str
) -> str:
    """Generate a ready-to-paste Optuna search space definition.

    Produces a complete ``objective`` function stub with one
    ``trial.suggest_*`` call per parameter, annotated with the HPF action
    and the short reasoning string.  Parameters with action REMOVE are
    emitted as comments so the user can see what was dropped and why.

    Parameters
    ----------
    suggestions:
        Ordered list of ParameterSuggestion objects, typically the direct
        output of ``RangeSuggester.suggest()``.
    study_name:
        Human-readable name of the Optuna study, used in the file header.

    Returns
    -------
    str
        A multi-line Python string ready to be copied into an Optuna script.
    """
    lines: list[str] = [
        f"# Updated search space for study: {study_name}",
        "# Generated by HPF — copy this into your objective function",
        "",
        "def objective(trial):",
    ]

    for s in suggestions:
        action_tag = s.action.value.upper()

        if s.action == SuggestionAction.REMOVE:
            # Emit as a comment — don't generate a suggest call.
            lines.append(
                f"    # [REMOVE] {s.name} — {s.reasoning}"
            )
            continue

        # Build the comment line above the suggest call.
        comment_suffix = _truncate(s.reasoning, 72 - len(s.name) - len(action_tag) - 8)
        if s.action == SuggestionAction.KEEP:
            lines.append(f"    # [{action_tag}] {s.name}")
        else:
            lines.append(f"    # [{action_tag}] {s.name} — {comment_suffix}")

        # Build the suggest call.
        suggest_call = _build_suggest_call(s)
        lines.append(f"    {s.name} = {suggest_call}")
        lines.append("")

    lines += [
        "    # ... your model training code here ...",
        "    pass",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_suggest_call(s: ParameterSuggestion) -> str:
    """Return the ``trial.suggest_*`` expression for *s* (no leading indent)."""
    name_repr = repr(s.name)

    if s.param_type == ParameterType.CATEGORICAL:
        choices = _effective_choices(s)
        return f"trial.suggest_categorical({name_repr}, {choices!r})"

    # Resolve the effective numeric bounds.
    low = s.suggested_low if s.suggested_low is not None else s.original_low
    high = s.suggested_high if s.suggested_high is not None else s.original_high
    use_log = s.suggested_scale == ParameterScale.LOG

    low_str = _fmt(low)
    high_str = _fmt(high)

    if s.param_type == ParameterType.INT:
        if use_log:
            return (
                f"trial.suggest_int({name_repr}, {low_str}, {high_str}, log=True)"
            )
        return f"trial.suggest_int({name_repr}, {low_str}, {high_str})"

    # FLOAT (default)
    if use_log:
        return (
            f"trial.suggest_float({name_repr}, {low_str}, {high_str}, log=True)"
        )
    return f"trial.suggest_float({name_repr}, {low_str}, {high_str})"


def _effective_choices(s: ParameterSuggestion) -> list[Any]:
    """Return the choices list to use in generated code.

    For NARROW categoricals the intent is to drop unused choices, but
    ``ParameterSuggestion`` doesn't carry the filtered list separately —
    the original list is stored in ``original_choices``.  Until the model
    is extended to carry ``suggested_choices``, we return the originals
    and let the user trim manually (the reasoning string explains which
    to drop).
    """
    return s.original_choices or []


def _fmt(value: float | None) -> str:
    """Format a numeric boundary for Optuna code output."""
    if value is None:
        return "None"
    if value == int(value):
        return str(int(value))
    if abs(value) < 1e-3 or abs(value) >= 1e6:
        return f"{value:.4e}"
    return f"{value:.6g}"


def _truncate(text: str, max_len: int) -> str:
    """Truncate *text* to *max_len* characters, appending '…' if needed."""
    if max_len <= 0:
        return ""
    if len(text) <= max_len:
        return text
    return text[: max(0, max_len - 1)] + "…"
